import crypto from 'node:crypto';
import { AsyncLocalStorage } from 'node:async_hooks';

const requestContextStore = new AsyncLocalStorage();
const MAX_RECENT_LOGS = 40;

export const ACTIVITY_LOG_FIELDS = [
  {
    field: 'trace_id',
    required: true,
    description: 'Request trace identifier. Reuses x-trace-id when provided, otherwise generated by activity-service.',
  },
  {
    field: 'user_id',
    required: false,
    description: 'Authenticated customer id resolved from bearer session.',
  },
  {
    field: 'activity_id',
    required: false,
    description: 'Activity id involved in the current request.',
  },
  {
    field: 'route',
    required: true,
    description: 'Observed HTTP route in the form "METHOD /path".',
  },
  {
    field: 'result',
    required: true,
    description: 'Normalized request result: success or fail.',
  },
];

export const ACTIVITY_ERROR_CATALOG = [
  {
    code: 'INVALID_ACTIVITY_ID',
    category: 'validation',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'Activity id is missing or invalid.',
  },
  {
    code: 'ACTIVITY_NOT_FOUND',
    category: 'resource',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'Activity does not exist in activity-service owned scope.',
  },
  {
    code: 'ACTIVITY_NOT_AVAILABLE',
    category: 'business_rule',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'Activity exists but is not visible to the current actor.',
  },
  {
    code: 'ALREADY_COMPLETED',
    category: 'idempotency',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'Same user already completed this activity today.',
  },
  {
    code: 'NEED_BASIC_VERIFY',
    category: 'auth_precondition',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'User must complete basic verification before activity completion.',
  },
  {
    code: 'ACTIVITY_POINTS_UPSTREAM_UNAVAILABLE',
    category: 'upstream',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'points-service is temporarily unavailable for reward settlement.',
  },
  {
    code: 'ACTIVITY_POINTS_CONTRACT_REJECTED',
    category: 'contract',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'points-service rejected the activity reward settlement contract call.',
  },
  {
    code: 'INVALID_ACTIVITY_REWARD_USER',
    category: 'validation',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'points-service rejected reward settlement because user id is invalid.',
  },
  {
    code: 'INVALID_ACTIVITY_REWARD_ACTIVITY_ID',
    category: 'validation',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'points-service rejected reward settlement because activity id is invalid.',
  },
  {
    code: 'INVALID_ACTIVITY_REWARD_POINTS',
    category: 'business_rule',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'points-service rejected reward settlement because reward points are invalid.',
  },
  {
    code: 'INVALID_ACTIVITY_REWARD_DATE',
    category: 'validation',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'points-service rejected reward settlement because completion date is invalid.',
  },
  {
    code: 'ACTIVITY_REWARD_SETTLEMENT_FAILED',
    category: 'system',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'points-service failed before reward posting completed.',
  },
  {
    code: 'UNAUTHORIZED',
    category: 'auth',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'Bearer token missing or invalid.',
  },
  {
    code: 'CSRF_INVALID',
    category: 'auth',
    routes: ['POST /api/activities/:id/complete'],
    meaning: 'Shared CSRF verification failed.',
  },
];

const createRuntimeState = () => ({
  startedAt: new Date().toISOString(),
  operations: {
    activityComplete: { success: 0, fail: 0 },
  },
  errorCounts: new Map(),
  recentLogs: [],
});

let runtimeState = createRuntimeState();

function toPositiveNumber(value) {
  const n = Number(value);
  return Number.isFinite(n) && n > 0 ? n : null;
}

function toNullableString(value) {
  const text = String(value ?? '').trim();
  return text || null;
}

function currentRequestContext() {
  return requestContextStore.getStore() || null;
}

function trimRecentLogs() {
  if (runtimeState.recentLogs.length <= MAX_RECENT_LOGS) return;
  runtimeState.recentLogs.splice(0, runtimeState.recentLogs.length - MAX_RECENT_LOGS);
}

function resolveTraceId(req) {
  const incomingTraceId = String(req.headers['x-trace-id'] || '').trim();
  const incomingRequestId = String(req.headers['x-request-id'] || '').trim();
  if (incomingTraceId) return incomingTraceId;
  if (incomingRequestId) return incomingRequestId;
  return `act_${Date.now()}_${crypto.randomUUID()}`;
}

function summarizeRate(counter) {
  const success = Number(counter?.success || 0);
  const fail = Number(counter?.fail || 0);
  const total = success + fail;
  const successRate = total > 0 ? Number((success / total).toFixed(4)) : 0;
  return {
    success,
    fail,
    total,
    successRate,
    successRatePct: Number((successRate * 100).toFixed(2)),
  };
}

function incrementErrorCount(code) {
  const key = String(code || '').trim();
  if (!key) return;
  runtimeState.errorCounts.set(key, Number(runtimeState.errorCounts.get(key) || 0) + 1);
}

function classifyActivityError(code) {
  const key = String(code || '').trim();
  if (!key) return null;
  return ACTIVITY_ERROR_CATALOG.find((item) => item.code === key) || null;
}

function pushRequestLog(entry) {
  runtimeState.recentLogs.push(entry);
  trimRecentLogs();
  console.log(`[activity-service] ${JSON.stringify(entry)}`);
}

function resolveOperationFromRoute(route) {
  const key = String(route || '').trim().toUpperCase();
  if (/^POST \/API\/ACTIVITIES\/[^/]+\/COMPLETE$/.test(key)) return 'activityComplete';
  return '';
}

function finalizeRequestLog({ req, res, startedAt, context }) {
  const result = context.result === 'success' || context.result === 'fail' ? context.result : res.statusCode >= 400 ? 'fail' : 'success';
  const responseCode = toNullableString(res.locals?.activityResponseBody?.code);
  const errorCode = toNullableString(context.error_code || responseCode);
  const operationName = context.operation_name || resolveOperationFromRoute(context.route);

  if (result === 'fail' && errorCode && !context.error_counted) {
    incrementErrorCount(errorCode);
    context.error_counted = true;
  }
  if (result === 'fail' && operationName && !context.operation_recorded && runtimeState.operations[operationName]) {
    runtimeState.operations[operationName].fail += 1;
    context.operation_recorded = true;
  }

  pushRequestLog({
    ts: new Date().toISOString(),
    trace_id: context.trace_id,
    request_id: context.request_id,
    user_id: toPositiveNumber(context.user_id),
    activity_id: toPositiveNumber(context.activity_id),
    route: context.route || `${String(req.method || 'GET').toUpperCase()} ${String(req.path || '')}`,
    result,
    status_code: Number(res.statusCode || 0),
    duration_ms: Number(Date.now() - startedAt),
    error_code: errorCode,
    error_category: errorCode ? classifyActivityError(errorCode)?.category || 'unknown' : null,
  });
}

export function createActivityObservabilityMiddleware() {
  return (req, res, next) => {
    const startedAt = Date.now();
    const traceId = resolveTraceId(req);
    const originalJson = res.json.bind(res);
    const context = {
      trace_id: traceId,
      request_id: String(req.headers['x-request-id'] || '').trim() || traceId,
      user_id: toPositiveNumber(req.user?.id ?? req.actor?.actorId),
      activity_id: null,
      route: `${String(req.method || 'GET').toUpperCase()} ${String(req.path || '')}`,
      result: 'pending',
      error_code: null,
      operation_name: '',
      operation_recorded: false,
      error_counted: false,
    };

    req.traceId = traceId;
    req.requestId = context.request_id;
    res.setHeader('x-trace-id', traceId);
    res.setHeader('x-request-id', context.request_id);
    res.setHeader('x-service-name', 'activity-service');
    res.json = (body) => {
      res.locals.activityResponseBody = body;
      return originalJson(body);
    };
    res.on('finish', () => finalizeRequestLog({ req, res, startedAt, context }));

    requestContextStore.run(context, () => next());
  };
}

export function setActivityRequestContext(patch = {}) {
  const context = currentRequestContext();
  if (!context) return;
  if (Object.prototype.hasOwnProperty.call(patch, 'trace_id')) {
    context.trace_id = toNullableString(patch.trace_id) || context.trace_id;
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'request_id')) {
    context.request_id = toNullableString(patch.request_id) || context.request_id;
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'user_id')) {
    context.user_id = toPositiveNumber(patch.user_id);
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'activity_id')) {
    context.activity_id = toPositiveNumber(patch.activity_id);
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'route')) {
    context.route = toNullableString(patch.route) || context.route;
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'result')) {
    const result = String(patch.result || '').trim().toLowerCase();
    if (result === 'success' || result === 'fail') context.result = result;
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'error_code')) {
    context.error_code = toNullableString(patch.error_code);
  }
}

function markActivityRequestSuccess(patch = {}) {
  setActivityRequestContext({
    ...patch,
    result: 'success',
    error_code: null,
  });
}

function markActivityRequestFail(code, patch = {}) {
  incrementErrorCount(code);
  setActivityRequestContext({
    ...patch,
    result: 'fail',
    error_code: code,
  });
  const context = currentRequestContext();
  if (context) context.error_counted = true;
}

function normalizeOperationName(name) {
  if (name === 'activityComplete' || name === 'activity-complete') return 'activityComplete';
  return '';
}

export function recordActivityOperationOutcome(operationName, { result, code, patch } = {}) {
  const key = normalizeOperationName(operationName);
  if (!key) return;
  const context = currentRequestContext();
  const normalizedResult = String(result || '').trim().toLowerCase() === 'success' ? 'success' : 'fail';
  runtimeState.operations[key][normalizedResult] += 1;
  if (context) {
    context.operation_name = key;
    context.operation_recorded = true;
  }
  if (normalizedResult === 'success') {
    markActivityRequestSuccess(patch);
    return;
  }
  markActivityRequestFail(code, patch);
}

export function getActivityObservabilitySnapshot() {
  return {
    ok: true,
    service: 'activity-service',
    startedAt: runtimeState.startedAt,
    metrics: {
      activityComplete: summarizeRate(runtimeState.operations.activityComplete),
      errorCounts: Array.from(runtimeState.errorCounts.entries())
        .map(([code, count]) => ({
          code,
          category: classifyActivityError(code)?.category || 'unknown',
          count: Number(count || 0),
        }))
        .sort((a, b) => a.code.localeCompare(b.code)),
    },
    logFieldSpec: ACTIVITY_LOG_FIELDS,
    recentLogs: [...runtimeState.recentLogs],
    errorCatalog: ACTIVITY_ERROR_CATALOG,
  };
}

export function resetActivityObservability() {
  runtimeState = createRuntimeState();
}
