export const C_ERROR_CODES_V1 = [
  'INVALID_MOBILE',
  'SMS_LIMIT_REACHED',
  'INVALID_NAME',
  'INVALID_CODE',
  'CODE_NOT_FOUND',
  'CODE_EXPIRED',
  'UNAUTHORIZED',
  'NEED_BASIC_VERIFY',
  'ALREADY_SIGNED',
  'ITEM_NOT_FOUND',
  'OUT_OF_STOCK',
  'INSUFFICIENT_POINTS',
  'REDEMPTION_NOT_FOUND',
  'ALREADY_WRITTEN_OFF',
  'INVALID_TOKEN',
  'TOKEN_EXPIRED',
] as const;

export type CErrorCodeV1 = (typeof C_ERROR_CODES_V1)[number];

