export const NOTICE_COPY = {
  cCameraScanStarting: '正在启动相机扫描...',
  cPolicySubmitSuccess: '保单提交成功！',
  cSignInSuccess: '签到成功！',
  cSignUpSuccess: '报名成功！',
  cJoinDeductSuccess: '报名成功！扣除50积分。',
  cSignInRewardPrefix: '签到成功，获得',
  cTaskCompleteRewardPrefix: '任务完成，获得',
  cPointsSuffixBang: '积分！',
  cRedeemSuccessWriteoffHint: '兑换成功，可在“我的兑换”中核销',
  cActivityJoinedDuplicated: '该活动已参与过',
  cActivityJoinRewardPrefix: '参与成功，获得',
  cWriteoffSuccess: '核销成功！',
  cLoadingLuckyWheel: '正在加载幸运大转盘...',
  cLoadingQuiz: '正在加载知识小考场...',
  cCourseCompleteRewardPrefix: '恭喜！完成学习，获得 ',
  cCourseCompleteRewardSuffix: ' 积分',
  shareLinkCopied: '分享链接已复制',
  shareFallbackPrefix: '请手动复制此链接分享：',
  shareFailedRetry: '分享失败，请重试',
  permissionSaved: '权限已保存',
  templateCreateRoleRequired: '仅平台管理员、公司管理员、团队主管或业务员可新增模板',
  pagePermissionDenied: '该页面无权限，请在权限管理中为公司管理员勾选后再访问',
  createEmployeeInPFirst: '请先在P端创建员工',
} as const;
