export const ACTION_COPY = {
  createActivity: '新建活动',
  createRule: '新建规则',
  addTeam: '新增团队',
  query: '查询',
  reset: '重置',
  refresh: '刷新',
  filter: '筛选',
  refreshStats: '刷新统计',
  saveDraft: '保存草稿',
  stopPublish: '停止发布',
  view: '查看',
  viewAll: '查看全部',
  viewFamilyMembers: '查看家庭成员',
  edit: '编辑',
  viewMore: '查看更多',
  preview: '预览',
  previewMall: '预览商城',
  save: '保存',
  saving: '保存中...',
  saveChanges: '保存修改',
  saveAndPublish: '保存并发布',
  saveConfig: '保存配置',
  discardEdit: '放弃编辑',
  manualInputWriteoffCode: '手动输入核销码',
  cGetCode: '获取验证码',
  cSubmitAuth: '提交认证',
  cPointsDetail: '积分明细',
  cRedeemNow: '立即兑换',
  cJoinNow: '立即参与',
  cAuthTitle: '实名认证',
  cAuthNameLabel: '真实姓名',
  cAuthPhoneLabel: '手机号码',
  cAuthCodeLabel: '验证码',
  cAuthNamePlaceholder: '请输入您的真实姓名',
  cAuthPhonePlaceholder: '请输入您的手机号码',
  cAuthCodePlaceholder: '请输入验证码',
  cAuthIntro: '为了保障您的权益，参与活动及兑换奖品前需完成实名认证。',
  cMallTitle: '积分商城',
  cMallBalanceTitle: '我的可用积分',
  cMallProductListTitle: '商品列表',
  cMallActivityListTitle: '活动列表',
  cMallActivityFallbackAlt: '商城活动',
  cMallRealtimeSync: '积分实时同步',
  cMallInventoryPrefix: '库存 ',
  cMallRewardPrefix: '奖励 ',
  cLoading: '加载中...',
  cNoActivities: '暂无活动',
  cSoldOut: '已兑完',
  cPointsInsufficient: '积分不足',
  cProfileTitle: '个人中心',
  cWechatNicknameFallback: '微信昵称',
  cGoVerify: '去实名',
  cVerified: '已实名',
  cEditProfile: '编辑资料',
  cMyPoints: '我的积分',
  cGoRedeem: '去兑换',
  cMyExchanges: '我的兑换',
  cMall: '积分商城',
  cWriteoffNow: '去核销',
  cDemoRedeemProductName: '美的智能电饭煲',
  cDemoRedeemDatePrefix: '兑换日期: ',
  cStudyRecord: '学习记录',
  cMyFavorites: '我的收藏',
  cFamilyManagement: '家庭成员管理',
  cFamilyMembersAddedPrefix: '已添加 ',
  cFamilyMembersAddedSuffix: ' 位成员',
  cMyPolicies: '我的保单',
  cPolicyPendingPaySuffix: ' 待支付',
  cMyActivities: '我的活动',
  cMyAdvisor: '我的顾问',
  cAdvisorOnline: '在线咨询',
  cSettings: '设置',
  cNeedHelp: '需要帮助吗？',
  cServiceHotlineHint: '点击拨打 24小时客服热线',
  cInsuranceManagementTitle: '保障管理',
  cInsuranceTabOverview: '总览',
  cInsuranceTabPolicyList: '保单列表',
  cLearningTitle: '知识学习',
  cLearningTabClass: '保险课堂',
  cLearningTabGames: '趣味游戏',
  cLearningTabTools: '实用工具',
  cMyExchangesTitle: '我的兑换',
  cTabAll: '全部',
  cTabPendingWriteoff: '待核销',
  cTabCompleted: '已完成',
  cStatusExpired: '已过期',
  cStatusRunning: '进行中',
  cStatusDraft: '草稿',
  cStatusOffline: '已下线',
  cExchangeDatePrefix: '兑换日期：',
  cCouponCodePrefix: '券码：',
  cCompletedWriteoffPrefix: '已于 ',
  cCompletedWriteoffSuffix: ' 完成核销',
  cExpiredHint: '有效期已过',
  cUploadPolicyTitle: '上传保单',
  cUploadOcrTitle: '拍照自动识别',
  cUploadOcrHint: '系统将自动提取保单关键信息，省时省力',
  cUploadClickPhoto: '点击拍照上传',
  cUploadPhotoHint: '支持纸质保单拍照或相册图片',
  cUploadOrManual: '或 手动输入详情',
  cUploadCompanyLabel: '保险公司',
  cUploadCompanyPlaceholder: '请选择保险公司',
  cUploadCompanyOptionPingan: '中国平安保险',
  cUploadCompanyOptionGuoshou: '中国人寿保险',
  cUploadCompanyOptionPacific: '太平洋保险',
  cUploadCompanyOptionAia: '友邦保险',
  cUploadDemoPolicyName: '平安福21重疾险',
  cUploadDemoApplicantName: '张三',
  cUploadDemoInsuredName: '张三',
  cUploadPolicyNameLabel: '保险名称',
  cUploadPolicyNamePlaceholder: '输入保单上的险种全称',
  cUploadApplicantLabel: '投保人',
  cUploadInsuredLabel: '被保险人',
  cUploadNamePlaceholder: '姓名',
  cUploadDateLabel: '投保时间',
  cUploadPayPeriodLabel: '缴费期间',
  cUploadCoveragePeriodLabel: '保障期间',
  cUploadPayPeriodSingle: '趸交',
  cUploadPayPeriod5Years: '5年交',
  cUploadPayPeriod10Years: '10年交',
  cUploadPayPeriod20Years: '20年交',
  cUploadPayPeriod30Years: '30年交',
  cUploadCoverageLifelong: '终身',
  cUploadCoverage20Years: '20年',
  cUploadCoverage30Years: '30年',
  cUploadCoverageTo70: '至70岁',
  cUploadCoverageTo80: '至80岁',
  cUploadAmountLabel: '保额 (元)',
  cUploadFirstPremiumLabel: '首期保费 (元)',
  cUploadSubmit: '确认并提交',
  cPolicyDetailTitle: '保单详情',
  cPolicyStatusActive: '保障中',
  cPolicyNoPrefix: '#',
  cPolicyInfoTitle: '投保信息',
  cPolicyMaskedName: '张*三',
  cPolicyDemoCoveragePeriod: '2024-01-01 至 2024-12-31',
  cPolicyApplicant: '投保人',
  cPolicyInsured: '被保险人',
  cPolicyCoveragePeriod: '保险期间',
  cPolicyAnnualPremium: '年度保费',
  cPolicyCoverageAmount: '保障额度',
  cPolicyCoverageLimitUnit: '万',
  cPolicyGeneralMedicalLimit: '300万',
  cPolicyCriticalMedicalLimit: '600万',
  cPolicyLimitEn: 'Limit',
  cPolicyResponsibilityTitle: '保障责任',
  cPolicyGeneralMedical: '一般医疗保险金',
  cPolicyGeneralMedicalDesc: '含住院/门诊手术/住院前后门诊',
  cPolicyCriticalMedical: '重疾医疗保险金',
  cPolicyCriticalMedicalDesc: '120种特定重大疾病',
  cPolicyExclusionTitle: '免责条款与投保告知',
  cPolicyExclusionDesc: '请务必阅读，了解不予赔付的情形',
  cPolicyPaymentHistory: '缴费记录',
  cPolicyPaymentDate: '缴费日期',
  cPolicyPaymentAmount: '金额',
  cPolicyFirstPayment: '年度首缴',
  cPolicyPaymentSuccess: '支付成功',
  cPolicyContactAdvisor: '联系顾问',
  cPolicyOnlineClaim: '在线理赔',
  cOverviewTotalCoverage: '总保障额度 (元)',
  cOverviewValidPolicies: '有效保单',
  cOverviewPolicyCountSuffix: '份',
  cOverviewAnnualPremium: '年度总保费',
  cOverviewFamilyTitle: '家庭成员保障',
  cOverviewAddMember: '添加成员',
  cOverviewRemindersTitle: '近期提醒',
  cOverviewRenewalReminder: '车险续保提醒',
  cOverviewDaysLeftPrefix: '剩 ',
  cOverviewDaysLeftSuffix: ' 天',
  cOverviewRenewalPolicyExpiring: '您的沪A·*****保单即将到期',
  cOverviewRenewNow: '立即续保',
  cOverviewBirthdayReminder: '儿子生日提醒',
  cOverviewTomorrow: '明天',
  cOverviewBirthdayGiftHint: '别忘了为他准备生日礼物哦',
  cOverviewViewBenefit: '查看福利',
  cOverviewReportReady: '体检报告已生成',
  cOverviewDaysAgo: '3天前',
  cOverviewReportUpdated: '年度健康体检结果已更新',
  cOverviewRead: '已读',
  cCategoryAll: '全部',
  cLearningCategorySenior: '养老',
  cLearningCategoryMedical: '医疗',
  cLearningCategoryChild: '少儿',
  cLearningCategoryFinance: '理财',
  cLearningCategoryClaim: '理赔',
  cLearningProgressTitle: '我的课程进度',
  cLearningLoadingCourses: '课程加载中...',
  cLearningNoCourses: '暂无可学习课程',
  cCourseDetailTitle: '课程详情',
  cCourseCurrentProgress: '当前学习进度',
  cCourseRewardPrefix: '学习可得 ',
  cCourseContentTitle: '知识文案',
  cCourseExtraIntro: '本课程将为您详细解读相关政策与条款，帮助您更好地理解保险产品，为您的家庭提供更全面的保障。',
  cCourseTipsTitle: '💡 学习建议：',
  cCourseTip1: '建议在安静的环境下观看',
  cCourseTip2: '结合自身实际情况进行思考',
  cCourseTip3: '如有疑问可随时联系您的专属顾问',
  cCourseCompleteAction: '完成学习领积分',
  cLearningProgressPrefix: '学习进度 ',
  cLearningTypeArticle: '文章',
  cLearningActionStart: '开始学习',
  cDemoCourse1Title: '如何使用手机申领医保报销',
  cDemoCourse1Desc: '手把手教您在手机上操作，简单又省时',
  cDemoCourse1TypeLabel: '视频课',
  cDemoCourse1TimeLeft: '2 分钟',
  cDemoCourse1Action: '继续学习',
  cDemoCourse1Content: '本节课程将详细演示如何通过官方APP或微信小程序，在线提交医疗报销凭证。无需线下排队，只需准备好发票、病历等材料的照片，跟着视频一步步操作即可完成申领。',
  cDemoCourse2Title: '三分钟看懂您的保单保障',
  cDemoCourse2Desc: '用通俗易懂的漫画带您理清保障范围',
  cDemoCourse2TypeLabel: '趣味漫画',
  cDemoCourse2TimeLeft: '约 3 分钟',
  cDemoCourse2Action: '开始学习',
  cDemoCourse2Content: '买完保险却不知道保什么？这篇漫画用生动的场景和比喻，帮您快速看懂保单中的核心条款：重疾险保哪些病？医疗险怎么报销？意外险包含哪些意外？让您的保单不再是“天书”。',
  cDemoCourse3Title: '2024养老金调整政策解读',
  cDemoCourse3Desc: '为您划重点，看看每月能多领多少钱',
  cDemoCourse3TypeLabel: '实用图文',
  cDemoCourse3TimeLeft: '剩 5 分钟',
  cDemoCourse3Action: '继续阅读',
  cDemoCourse3Content: '2024年国家基本养老金上调政策正式发布！本次调整采取定额调整、挂钩调整与适当倾斜相结合的办法。本文将为您详细解读调整比例、计算方法以及高龄退休人员的特殊倾斜政策。',
  cDemoGame1Title: '风险大作战',
  cDemoGame1Desc: '识别生活中的潜在风险，保护你的小家',
  cDemoGame1Category: '风险认知',
  cDemoGame1BestScore: '2500分',
  cDemoGame2Title: '条款连连看',
  cDemoGame2Desc: '消除晦涩难懂的保险术语，轻松学知识',
  cDemoGame2Category: '产品理解',
  cDemoGame2BestScore: '通关第5关',
  cDemoPolicyCompany1: '平安健康保险股份有限公司',
  cDemoPolicyName1: '尊享e生2024',
  cDemoPolicyType1: '医疗',
  cDemoPolicyAmount1: '300.00万',
  cDemoPolicyCompany2: '中国人寿保险',
  cDemoPolicyName2: '国寿福重疾险',
  cDemoPolicyType2: '重疾',
  cDemoPolicyAmount2: '50.00万',
  cDemoPolicyCompany3: '太平洋保险',
  cDemoPolicyName3: '太保意外伤害险',
  cDemoPolicyType3: '意外',
  cDemoPolicyAmount3: '100.00万',
  cOverviewMemberSelf: '本人',
  cOverviewMemberSpouse: '妻子',
  cOverviewMemberChild: '儿子',
  cOverviewMemberScoreSuffix: '分',
  cFunGameDifficulty: '难度:',
  cFunGameBestPrefix: '最佳: ',
  cFunGameStart: '开始游戏',
  cPopularGamesTitle: '热门游戏',
  cPopularGameLuckyWheelTitle: '幸运大转盘',
  cPopularGameLuckyWheelDesc: '100%中奖 赢积分',
  cPopularGameQuizTitle: '知识小考场',
  cPopularGameQuizDesc: '答对5题 翻倍奖励',
  cPolicyListAmount: '保障额度',
  cPolicyListNextPayDate: '下次缴费日',
  cToolPensionCalc: '养老金计算器',
  cToolPensionCalcDesc: '输入参数，可视化未来养老资金缺口',
  cToolCoverageGap: '保障缺口分析',
  cToolCoverageGapDesc: '问答式引导，生成家庭风险矩阵报告',
  cToolClaimProgress: '理赔进度查询',
  cToolClaimProgressDesc: '关联已托管保单，实时查询理赔状态',
  cExchangeDetailTitle: '兑换详情',
  cExchangePointSuffix: ' 积分',
  cExchangeOrderNo: '订单编号',
  cExchangeTime: '兑换时间',
  cExchangeStatus: '状态',
  cExchangeUsageTitle: '使用说明',
  cExchangeRule1: '请向门店工作人员出示核销二维码',
  cExchangeRule2: '二维码截图无效，请在现场打开此页面',
  cExchangeRule3: '商品一经核销，不可退换',
  cExchangeRule4: '有效期至：2024-12-31',
  cExchangeShowWriteoffCode: '出示核销码',
  cExchangeShowToClerk: '向店员出示此码',
  cExchangeDontShareCode: '请勿将此码分享给他人',
  cExchangeWritingOff: '核销中...',
  cExchangeConfirmWriteoff: '确认核销',
  cNavHome: '首页',
  cNavLearning: '知识学习',
  cNavActivities: '活动中心',
  cNavInsurance: '保障管理',
  cNavProfile: '我的',
  cHeaderHello: '你好',
  cHeaderMorning: '早上好',
  cHeaderAfternoon: '下午好',
  cHeaderEvening: '晚上好',
  cHeaderDefaultUserName: '张叔叔',
  cHeaderWelcomeHint: '今天也要记得领鸡蛋哦',
  cFeatureInsurance: '保障管理',
  cFeatureClass: '保险课堂',
  cFeatureSignIn: '每日签到',
  cFeatureShare: '分享有礼',
  cPopupSignInGiftTitle: '每日签到好礼',
  cPopupSignInGiftDescPrefix: '今天签到可获得 ',
  cPopupSignInGiftDescSuffix: ' 积分',
  cPopupSignInGiftDescTail: '连续签到奖励更丰富哦！',
  cPopupSignInAction: '立即签到领积分',
  cActivitiesTitle: '活动中心',
  cActivityDetailTitle: '活动详情',
  cActivityTagHot: '热门活动',
  cActivityTagKnowledge: '保险知识',
  cActivityTagReward: '高额奖励',
  cActivityRequiredPoints: '报名所需积分',
  cActivitySeatsLeft: '当前剩余名额',
  cActivitySeatsUnit: ' 位',
  cActivityIntroTitle: '活动简介',
  cActivityIntroParagraph1Prefix: '欢迎来到“',
  cActivityIntroParagraph1Suffix: '”！这不仅是一次知识的较量，更是一次为家人建立安全感的心灵旅程。在本次挑战赛中，您将通过一系列精心设计的趣味任务，深入浅出地了解家庭保险的核心价值。',
  cActivityIntroParagraph2: '我们将带您模拟不同的家庭场景，学习如何评估风险、选择最适合家人的保障方案。无论您是理财达人还是保险小白，都能在这里收获实用的保障干货，为家庭构筑坚实的防护墙。',
  cActivityQuizTitle: '趣味答题',
  cActivityQuizDesc: '完成每日保险知识闯关，解锁高级保险技能点。',
  cActivityRewardTitle: '丰厚奖励',
  cActivityRewardDesc: '通过挑战即可赢取高达 500 积分奖励及电子荣誉证书。',
  cActivityRulesTitle: '活动规则',
  cActivityRule1: '活动有效期：2024年1月1日至2024年12月31日。',
  cActivityRule2: '报名成功后，需在7个工作日内开启首项任务，否则名额将自动失效。',
  cActivityRule3: '每个账号仅限参与一次，积分奖励将在挑战完成后即时到账。',
  cActivityFooterSlogan: '—— 保险让生活更美好 ——',
  cActivityTotal: '合计',
  cActivityApplyNow: '立即报名',
  cActivitiesMyPoints: '我的积分',
  cPointsUnit: '分',
  cTodayTaskProgress: '今日任务进度',
  cCompletedSuffix: ' 已完成',
  cHotActivitiesTitle: '热门活动',
  cHomeOngoingActivitiesTitle: '进行中活动',
  cHomeSignInEggTitle: '签到领鸡蛋',
  cHomeSignInEggDesc: '连续签到7天可换新鲜鸡蛋',
  cHomeFamilyChallengeTitle: '家庭保障挑战赛',
  cHomeFamilyChallengeDesc: '完善全家信息赢取话费',
  cActivitiesLoading: '活动加载中...',
  cBadgeCompetition: '智力竞赛',
  cBadgeInvite: '有奖推荐',
  cBadgeSignTask: '签到任务',
  cBadgeProfileComplete: '资料完善',
  cActivitySubtitleDefault: '参与活动可获得积分奖励',
  cActionInviteNow: '立即邀请',
  cActionViewDetail: '查看详情',
  cActionSignNow: '立即签到',
  cActionCompleteNow: '立即完成',
  cCompleted: '已完成',
  cPointsBannerTitle: '去兑换积分',
  cPointsBannerSubtitle: '超值好礼随心兑，鸡蛋、话费等你拿',
  cPointsBannerAction: '去积分商城',
  cLatestNewsTitle: '最新资讯',
  cLatestNewsRefresh: '换一批',
  cLatestNewsCardTitle: '2024年养老保险新政策解读',
  cLatestNewsCardDesc: '详细了解最新推出的居家养老补助计划，帮助您更好地规划晚年生活，享受无忧的退休时光...',
  cAdvisorTitle: '您的专属顾问：小王',
  cAdvisorServiceDaysPrefix: '已为您服务 ',
  cAdvisorServiceDaysSuffix: ' 天',
  cAdvisorContact: '联系顾问',
} as const;
