export const VALIDATION_COPY = {
  cRealNameInvalid: '请输入2-20位中文姓名',
  cPhoneInvalid: '请输入正确的手机号码',
  cCodeInvalid6: '请输入6位验证码',
  activityTitleRequired: '请输入活动标题',
  activityNameRequired: '请填写活动名称',
  tenantNameRequired: '请输入租户名称',
  adminEmailRequired: '请输入管理员邮箱',
  adminEmailInvalid: '管理员邮箱格式错误',
  initPasswordMin6: '初始密码至少6位',
  metricRuleRequiredFields: '请完整填写：指标名称、口径/公式、统计周期、数据源',
  eventIdPositiveInteger: '事件ID必须为正整数',
  eventNameRequired: '事件名称不能为空',
  eventSchemaInvalidJson: '属性定义JSON格式不正确',
  teamNameRequired: '团队名称不能为空',
  employeeBaseInfoRequired: '请输入姓名、工作邮箱和手机号',
  phoneInvalid11: '手机号格式错误，请输入11位手机号',
  teamRequired: '请选择所属团队',
  tagRuleTargetRequired: '请至少选择一个目标标签',
  learningTitleRequired: '请输入资料标题',
  learningFileRequired: '请至少上传一个文件',
  bProductNameRequired: '请输入商品名称',
  bActivityNameRequired: '请输入活动名称',
} as const;
