import crypto from 'node:crypto';
import { AsyncLocalStorage } from 'node:async_hooks';
import { appendAuditLog, appendDomainEvent } from '../../skeleton-c-v1/common/state.mjs';

const requestContextStore = new AsyncLocalStorage();
const MAX_RECENT_LOGS = 60;

export const POINTS_LOG_FIELDS = [
  {
    field: 'trace_id',
    required: true,
    description: 'Request trace identifier. Reuses x-trace-id when provided, otherwise generated by points-service.',
  },
  {
    field: 'user_id',
    required: false,
    description: 'Authenticated customer id resolved from bearer session. Null for anonymous reads or auth failures.',
  },
  {
    field: 'order_id',
    required: false,
    description: 'Order id involved in the transaction chain. Present for create/pay/cancel/refund/redeem/order detail flows.',
  },
  {
    field: 'redemption_id',
    required: false,
    description: 'Redemption id involved in the request. Present for redeem and writeoff flows.',
  },
  {
    field: 'route',
    required: true,
    description: 'Observed HTTP route in the form "METHOD /path".',
  },
  {
    field: 'result',
    required: true,
    description: 'Normalized request result: success or fail.',
  },
];

export const POINTS_PENDING_BRIDGE_METHODS = [
  {
    method: 'createOrder',
    file: '/Users/wenshuping/Documents/New project/insurance_code/insurance_code_full/src/lib/api.ts',
    status: 'defined_not_enabled',
    reason: 'C-side mall flow is frozen on single-step redeem, not two-step create/pay.',
  },
  {
    method: 'payOrder',
    file: '/Users/wenshuping/Documents/New project/insurance_code/insurance_code_full/src/lib/api.ts',
    status: 'defined_not_enabled',
    reason: 'C-side mall flow is frozen on single-step redeem, not two-step create/pay.',
  },
  {
    method: 'cancelOrder',
    file: '/Users/wenshuping/Documents/New project/insurance_code/insurance_code_full/src/lib/api.ts',
    status: 'defined_not_enabled',
    reason: 'No current C-side interaction entry for customer-initiated cancellation.',
  },
  {
    method: 'refundOrder',
    file: '/Users/wenshuping/Documents/New project/insurance_code/insurance_code_full/src/lib/api.ts',
    status: 'defined_not_enabled',
    reason: 'No current C-side interaction entry for customer-initiated refund.',
  },
];

export const POINTS_ERROR_CATALOG = [
  {
    code: 'INVALID_ACTIVITY_REWARD_USER',
    category: 'validation',
    routes: ['INTERNAL activity->points reward settlement'],
    meaning: 'Activity reward settlement requires a valid customer id.',
  },
  {
    code: 'INVALID_ACTIVITY_REWARD_ACTIVITY_ID',
    category: 'validation',
    routes: ['INTERNAL activity->points reward settlement'],
    meaning: 'Activity reward settlement requires a valid activity id.',
  },
  {
    code: 'INVALID_ACTIVITY_REWARD_DATE',
    category: 'validation',
    routes: ['INTERNAL activity->points reward settlement'],
    meaning: 'Activity reward settlement requires a valid completion date.',
  },
  {
    code: 'INVALID_ACTIVITY_REWARD_POINTS',
    category: 'business_rule',
    routes: ['INTERNAL activity->points reward settlement'],
    meaning: 'Activity reward settlement rejected an invalid reward amount.',
  },
  {
    code: 'ACTIVITY_REWARD_SETTLEMENT_FAILED',
    category: 'system',
    routes: ['INTERNAL activity->points reward settlement'],
    meaning: 'Activity reward settlement failed before points posting completed.',
  },
  {
    code: 'INVALID_LEARNING_REWARD_USER',
    category: 'validation',
    routes: ['INTERNAL learning->points reward settlement'],
    meaning: 'Learning reward settlement requires a valid customer id.',
  },
  {
    code: 'INVALID_LEARNING_REWARD_COURSE_ID',
    category: 'validation',
    routes: ['INTERNAL learning->points reward settlement'],
    meaning: 'Learning reward settlement requires a valid course id.',
  },
  {
    code: 'INVALID_LEARNING_REWARD_POINTS',
    category: 'business_rule',
    routes: ['INTERNAL learning->points reward settlement'],
    meaning: 'Learning reward settlement rejected an invalid reward amount.',
  },
  {
    code: 'LEARNING_REWARD_SETTLEMENT_FAILED',
    category: 'system',
    routes: ['INTERNAL learning->points reward settlement'],
    meaning: 'Learning reward settlement failed before points posting completed.',
  },
  {
    code: 'NEED_BASIC_VERIFY',
    category: 'auth_precondition',
    routes: ['POST /api/sign-in', 'POST /api/mall/redeem', 'POST /api/mall/activities/:id/join'],
    meaning: 'User has not completed the required basic identity verification.',
  },
  {
    code: 'UNAUTHORIZED',
    category: 'auth',
    routes: ['POST /api/sign-in', 'POST /api/redemptions/:id/writeoff'],
    meaning: 'Bearer token missing, invalid, or expired.',
  },
  {
    code: 'ALREADY_SIGNED',
    category: 'idempotency',
    routes: ['POST /api/sign-in'],
    meaning: 'Duplicate same-day sign-in request.',
  },
  {
    code: 'INVALID_ITEM_ID',
    category: 'validation',
    routes: ['POST /api/mall/redeem'],
    meaning: 'Redeem request carries an invalid or empty item id.',
  },
  {
    code: 'ITEM_NOT_FOUND',
    category: 'resource',
    routes: ['POST /api/mall/redeem', 'POST /api/orders', 'POST /api/orders/:id/pay'],
    meaning: 'Referenced product cannot be resolved from points-owned catalog.',
  },
  {
    code: 'ITEM_NOT_AVAILABLE',
    category: 'business_rule',
    routes: ['POST /api/mall/redeem'],
    meaning: 'Product exists but is not currently redeemable in the active tenant scope.',
  },
  {
    code: 'OUT_OF_STOCK',
    category: 'capacity',
    routes: ['POST /api/mall/redeem', 'POST /api/orders', 'POST /api/orders/:id/pay'],
    meaning: 'Requested product has insufficient stock.',
  },
  {
    code: 'INSUFFICIENT_POINTS',
    category: 'balance',
    routes: ['POST /api/mall/redeem', 'POST /api/orders/:id/pay'],
    meaning: 'Customer balance cannot cover the points payment.',
  },
  {
    code: 'INVALID_ACTIVITY_ID',
    category: 'validation',
    routes: ['POST /api/mall/activities/:id/join'],
    meaning: 'Mall activity id is invalid.',
  },
  {
    code: 'MALL_ACTIVITY_NOT_FOUND',
    category: 'resource',
    routes: ['POST /api/mall/activities/:id/join'],
    meaning: 'Mall activity does not exist.',
  },
  {
    code: 'MALL_ACTIVITY_NOT_AVAILABLE',
    category: 'business_rule',
    routes: ['POST /api/mall/activities/:id/join'],
    meaning: 'Mall activity exists but is not available for participation.',
  },
  {
    code: 'NO_PERMISSION',
    category: 'authorization',
    routes: ['GET /api/mall/items', 'GET /api/mall/activities', 'POST /api/mall/activities/:id/join'],
    meaning: 'Actor lacks permission to access or join the activity/catalog entry.',
  },
  {
    code: 'INVALID_PRODUCT_ID',
    category: 'validation',
    routes: ['POST /api/orders'],
    meaning: 'Order create request carries an invalid product id.',
  },
  {
    code: 'INVALID_ORDER_ID',
    category: 'validation',
    routes: ['GET /api/orders/:id', 'POST /api/orders/:id/pay', 'POST /api/orders/:id/cancel', 'POST /api/orders/:id/refund'],
    meaning: 'Order id is missing or not a positive integer.',
  },
  {
    code: 'ORDER_NOT_FOUND',
    category: 'resource',
    routes: ['GET /api/orders/:id', 'POST /api/orders/:id/pay', 'POST /api/orders/:id/cancel', 'POST /api/orders/:id/refund'],
    meaning: 'Referenced order does not exist in points-owned storage.',
  },
  {
    code: 'ORDER_FORBIDDEN',
    category: 'authorization',
    routes: ['GET /api/orders/:id', 'POST /api/orders/:id/pay', 'POST /api/orders/:id/cancel'],
    meaning: 'Actor is not allowed to access or mutate the target order.',
  },
  {
    code: 'ORDER_ALREADY_FULFILLED',
    category: 'business_rule',
    routes: ['POST /api/orders/:id/cancel', 'POST /api/orders/:id/refund'],
    meaning: 'Order has already been shipped or written off and can no longer be changed.',
  },
  {
    code: 'ORDER_NOT_PAID',
    category: 'business_rule',
    routes: ['POST /api/orders/:id/refund', 'POST /api/redemptions/:id/writeoff'],
    meaning: 'Order is not in a paid state required by the operation.',
  },
  {
    code: 'REDEMPTION_NOT_FOUND',
    category: 'resource',
    routes: ['POST /api/redemptions/:id/writeoff'],
    meaning: 'Redemption record does not exist for the current user.',
  },
  {
    code: 'ALREADY_WRITTEN_OFF',
    category: 'idempotency',
    routes: ['POST /api/redemptions/:id/writeoff'],
    meaning: 'Redemption has already been written off.',
  },
  {
    code: 'INVALID_TOKEN',
    category: 'validation',
    routes: ['POST /api/redemptions/:id/writeoff'],
    meaning: 'Writeoff token does not match the redemption record.',
  },
  {
    code: 'TOKEN_EXPIRED',
    category: 'business_rule',
    routes: ['POST /api/redemptions/:id/writeoff'],
    meaning: 'Writeoff token exists but has expired.',
  },
];

const createRuntimeState = () => ({
  startedAt: new Date().toISOString(),
  operations: {
    activityReward: { success: 0, fail: 0 },
    learningReward: { success: 0, fail: 0 },
    signIn: { success: 0, fail: 0 },
    redeem: { success: 0, fail: 0 },
    writeoff: { success: 0, fail: 0 },
  },
  orderTransitions: new Map(),
  pointsMovements: {
    creditCount: 0,
    debitCount: 0,
  },
  errorCounts: new Map(),
  recentLogs: [],
});

let runtimeState = createRuntimeState();

function toPositiveNumber(value) {
  const n = Number(value);
  return Number.isFinite(n) && n > 0 ? n : null;
}

function toNullableString(value) {
  const text = String(value ?? '').trim();
  return text || null;
}

function currentRequestContext() {
  return requestContextStore.getStore() || null;
}

function trimRecentLogs() {
  if (runtimeState.recentLogs.length <= MAX_RECENT_LOGS) return;
  runtimeState.recentLogs.splice(0, runtimeState.recentLogs.length - MAX_RECENT_LOGS);
}

function normalizeOperationName(name) {
  if (name === 'activityReward' || name === 'activity-reward') return 'activityReward';
  if (name === 'learningReward' || name === 'learning-reward') return 'learningReward';
  if (name === 'sign-in') return 'signIn';
  if (name === 'redeem') return 'redeem';
  if (name === 'writeoff') return 'writeoff';
  return '';
}

function resolveOperationFromRoute(route) {
  const key = String(route || '').trim().toUpperCase();
  if (key === 'INTERNAL ACTIVITY->POINTS REWARD SETTLEMENT') return 'activityReward';
  if (key === 'INTERNAL LEARNING->POINTS REWARD SETTLEMENT') return 'learningReward';
  if (key === 'POST /API/SIGN-IN') return 'signIn';
  if (key === 'POST /API/MALL/REDEEM') return 'redeem';
  if (/^POST \/API\/REDEMPTIONS\/[^/]+\/WRITEOFF$/.test(key)) return 'writeoff';
  return '';
}

function resolveTraceId(req) {
  const incomingTraceId = String(req.headers['x-trace-id'] || '').trim();
  const incomingRequestId = String(req.headers['x-request-id'] || '').trim();
  if (incomingTraceId) return incomingTraceId;
  if (incomingRequestId) return incomingRequestId;
  return `pts_${Date.now()}_${crypto.randomUUID()}`;
}

function summarizeRate(counter) {
  const success = Number(counter?.success || 0);
  const fail = Number(counter?.fail || 0);
  const total = success + fail;
  const successRate = total > 0 ? Number((success / total).toFixed(4)) : 0;
  return {
    success,
    fail,
    total,
    successRate,
    successRatePct: Number((successRate * 100).toFixed(2)),
  };
}

function incrementErrorCount(code) {
  const key = String(code || '').trim();
  if (!key) return;
  runtimeState.errorCounts.set(key, Number(runtimeState.errorCounts.get(key) || 0) + 1);
}

function classifyPointsError(code) {
  const key = String(code || '').trim();
  if (!key) return null;
  return POINTS_ERROR_CATALOG.find((item) => item.code === key) || null;
}

function pushRequestLog(entry) {
  runtimeState.recentLogs.push(entry);
  trimRecentLogs();
  console.log(`[points-service] ${JSON.stringify(entry)}`);
}

function pushSyntheticOperationLog({ result, code, patch }) {
  const traceId = toNullableString(patch?.trace_id) || `pts_internal_${Date.now()}_${crypto.randomUUID()}`;
  pushRequestLog({
    ts: new Date().toISOString(),
    trace_id: traceId,
    request_id: traceId,
    user_id: toPositiveNumber(patch?.user_id),
    order_id: toPositiveNumber(patch?.order_id),
    redemption_id: toPositiveNumber(patch?.redemption_id),
    route: toNullableString(patch?.route) || 'INTERNAL points-service contract',
    result,
    status_code: result === 'success' ? 200 : 500,
    duration_ms: 0,
    error_code: toNullableString(code),
    error_category: code ? classifyPointsError(code)?.category || 'unknown' : null,
  });
}

function finalizeRequestLog({ req, res, startedAt, context }) {
  const userId = toPositiveNumber(context.user_id ?? req.user?.id ?? req.actor?.actorId);
  const orderId = toPositiveNumber(context.order_id);
  const redemptionId = toPositiveNumber(context.redemption_id);
  const result = context.result === 'success' || context.result === 'fail' ? context.result : res.statusCode >= 400 ? 'fail' : 'success';
  const responseCode = toNullableString(res.locals?.pointsResponseBody?.code);
  const errorCode = toNullableString(context.error_code || responseCode);
  const operationName = context.operation_name || resolveOperationFromRoute(context.route);

  if (result === 'fail' && errorCode && !context.error_counted) {
    incrementErrorCount(errorCode);
    context.error_counted = true;
  }
  if (result === 'fail' && operationName && !context.operation_recorded && runtimeState.operations[operationName]) {
    runtimeState.operations[operationName].fail += 1;
    context.operation_recorded = true;
  }

  const entry = {
    ts: new Date().toISOString(),
    trace_id: context.trace_id,
    request_id: context.request_id,
    user_id: userId,
    order_id: orderId,
    redemption_id: redemptionId,
    route: context.route || `${String(req.method || 'GET').toUpperCase()} ${String(req.path || '')}`,
    result,
    status_code: Number(res.statusCode || 0),
    duration_ms: Number(Date.now() - startedAt),
    error_code: errorCode,
    error_category: errorCode ? classifyPointsError(errorCode)?.category || 'unknown' : null,
  };

  pushRequestLog(entry);
}

export function createPointsObservabilityMiddleware() {
  return (req, res, next) => {
    const startedAt = Date.now();
    const traceId = resolveTraceId(req);
    const originalJson = res.json.bind(res);
    const context = {
      trace_id: traceId,
      request_id: String(req.headers['x-request-id'] || '').trim() || traceId,
      user_id: toPositiveNumber(req.user?.id ?? req.actor?.actorId),
      order_id: null,
      redemption_id: null,
      route: `${String(req.method || 'GET').toUpperCase()} ${String(req.path || '')}`,
      result: 'pending',
      error_code: null,
      operation_name: '',
      operation_recorded: false,
      error_counted: false,
    };

    req.traceId = traceId;
    req.requestId = context.request_id;
    res.setHeader('x-trace-id', traceId);
    res.setHeader('x-request-id', context.request_id);
    res.setHeader('x-service-name', 'points-service');
    res.json = (body) => {
      res.locals.pointsResponseBody = body;
      return originalJson(body);
    };
    res.on('finish', () => finalizeRequestLog({ req, res, startedAt, context }));

    requestContextStore.run(context, () => next());
  };
}

export function setPointsRequestContext(patch = {}) {
  const context = currentRequestContext();
  if (!context) return;
  if (Object.prototype.hasOwnProperty.call(patch, 'trace_id')) {
    context.trace_id = toNullableString(patch.trace_id) || context.trace_id;
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'request_id')) {
    context.request_id = toNullableString(patch.request_id) || context.request_id;
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'user_id')) {
    context.user_id = toPositiveNumber(patch.user_id);
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'order_id')) {
    context.order_id = toPositiveNumber(patch.order_id);
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'redemption_id')) {
    context.redemption_id = toPositiveNumber(patch.redemption_id);
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'route')) {
    context.route = toNullableString(patch.route) || context.route;
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'result')) {
    const result = String(patch.result || '').trim().toLowerCase();
    if (result === 'success' || result === 'fail') context.result = result;
  }
  if (Object.prototype.hasOwnProperty.call(patch, 'error_code')) {
    context.error_code = toNullableString(patch.error_code);
  }
}

export function markPointsRequestSuccess(patch = {}) {
  setPointsRequestContext({
    ...patch,
    result: 'success',
    error_code: null,
  });
}

export function markPointsRequestFail(code, patch = {}) {
  incrementErrorCount(code);
  setPointsRequestContext({
    ...patch,
    result: 'fail',
    error_code: code,
  });
  const context = currentRequestContext();
  if (context) context.error_counted = true;
}

export function recordPointsOperationOutcome(operationName, { result, code, patch } = {}) {
  const key = normalizeOperationName(operationName);
  if (!key) return;
  const context = currentRequestContext();
  const normalizedResult = String(result || '').trim().toLowerCase() === 'success' ? 'success' : 'fail';
  runtimeState.operations[key][normalizedResult] += 1;
  if (context) {
    context.operation_name = key;
    context.operation_recorded = true;
  }
  if (normalizedResult === 'success') {
    markPointsRequestSuccess(patch);
    if (!context && patch?.route) pushSyntheticOperationLog({ result: normalizedResult, code: null, patch });
    return;
  }
  markPointsRequestFail(code, patch);
  if (!context && patch?.route) pushSyntheticOperationLog({ result: normalizedResult, code, patch });
}

export function recordOrderStatusTransition({ orderId, fromStatus, toStatus }) {
  const from = String(fromStatus || '').trim().toLowerCase() || 'unknown';
  const to = String(toStatus || '').trim().toLowerCase() || 'unknown';
  if (from === to) return;
  const key = `${from}->${to}`;
  runtimeState.orderTransitions.set(key, Number(runtimeState.orderTransitions.get(key) || 0) + 1);
  setPointsRequestContext({ order_id: orderId });
}

export function recordPointsMovement({ direction, userId, orderId = null, redemptionId = null }) {
  const normalizedDirection = String(direction || '').trim().toLowerCase();
  if (normalizedDirection === 'in') runtimeState.pointsMovements.creditCount += 1;
  if (normalizedDirection === 'out') runtimeState.pointsMovements.debitCount += 1;
  setPointsRequestContext({
    user_id: userId,
    order_id: orderId,
    redemption_id: redemptionId,
  });
}

export function appendPointsAuditLog(entry = {}) {
  const context = currentRequestContext();
  appendAuditLog({
    ...entry,
    traceId: entry.traceId || context?.trace_id || null,
    userId: entry.userId ?? context?.user_id ?? null,
    orderId: entry.orderId ?? context?.order_id ?? null,
    redemptionId: entry.redemptionId ?? context?.redemption_id ?? null,
    route: entry.route || context?.route || null,
    result: entry.result || context?.result || 'success',
  });
}

export function appendPointsDomainEvent(type, payload, options = {}) {
  const context = currentRequestContext();
  return appendDomainEvent(type, payload, {
    ...options,
    traceId: options.traceId || context?.trace_id || null,
  });
}

export function getPointsObservabilitySnapshot() {
  return {
    ok: true,
    service: 'points-service',
    startedAt: runtimeState.startedAt,
    metrics: {
      activityReward: summarizeRate(runtimeState.operations.activityReward),
      learningReward: summarizeRate(runtimeState.operations.learningReward),
      signIn: summarizeRate(runtimeState.operations.signIn),
      redeem: summarizeRate(runtimeState.operations.redeem),
      writeoff: summarizeRate(runtimeState.operations.writeoff),
      orderTransitions: Array.from(runtimeState.orderTransitions.entries())
        .map(([transition, count]) => ({
          transition,
          count: Number(count || 0),
        }))
        .sort((a, b) => a.transition.localeCompare(b.transition)),
      pointsMovements: {
        creditCount: Number(runtimeState.pointsMovements.creditCount || 0),
        debitCount: Number(runtimeState.pointsMovements.debitCount || 0),
      },
      errorCounts: Array.from(runtimeState.errorCounts.entries())
        .map(([code, count]) => ({
          code,
          category: classifyPointsError(code)?.category || 'unknown',
          count: Number(count || 0),
        }))
        .sort((a, b) => a.code.localeCompare(b.code)),
    },
    logFieldSpec: POINTS_LOG_FIELDS,
    recentLogs: [...runtimeState.recentLogs],
    pendingBridgeMethods: POINTS_PENDING_BRIDGE_METHODS,
    errorCatalog: POINTS_ERROR_CATALOG,
  };
}

export function resetPointsObservability() {
  runtimeState = createRuntimeState();
}
